import type { SecureStore } from './secureStore.ts'

/**
 * Where a device keeps the refresh token. Section 35's deferred choice, made on
 * 2026-08-31 against the two plugins that still exist for Capacitor 8.
 *
 * <p><strong>`@aparajita/capacitor-secure-storage`, and the deciding line was
 * the cipher mode.</strong> It states AES-GCM with a key generated by the
 * Android KeyStore, and GCM is authenticated: a tampered ciphertext is
 * *detected* rather than decrypted into rubbish. The alternative,
 * `capacitor-secure-storage-plugin`, names neither mode nor construction, and
 * keeps a branch for API levels below 18 that stores base64 - unreachable at
 * `minSdk 24`, and a path that exists in order to be reached one day. For a
 * thirty-day credential that opens every endpoint, the difference is not
 * academic.
 *
 * <p><strong>The web implementations are why this file must never be reachable
 * from a browser build, and reading them settled an argument.</strong>
 * `channel.ts` chose build-time selection over `Capacitor.isNativePlatform()`
 * on the *expectation* that secure-storage plugins ship a web shim backed by
 * `localStorage`. Both of them do: this one stores unencrypted and says so, the
 * other base64-encodes, which is an encoding anybody can reverse and not
 * encryption at all. Under runtime selection that shim would be in the bundle
 * served to every visitor, with nothing between it and the token but a branch
 * nobody must ever flip. The expectation is now evidence.
 *
 * <p><strong>`getItem`/`setItem`/`removeItem` rather than
 * `get`/`set`/`remove`.</strong> The latter trio round-trips JSON and can coerce
 * ISO strings back into dates. A refresh token is opaque: the application must
 * hand back the same bytes the server issued, and any transformation between
 * them is a way to return something subtly different. The string-only trio has
 * exactly the three signatures `SecureStore` declares.
 *
 * <p><strong>`removeItem` and not the plugin's `clear()`.</strong> `clear()`
 * removes every entry sharing the key prefix. Forgetting a session means
 * forgetting the session, and a method that widens as the application stores
 * more would go wrong quietly and much later.
 *
 * <p>No error handling here on purpose. `refresh.ts` already wraps the whole
 * attempt and treats any failure - a refusing store, a corrupted entry, a
 * missing one - as "no usable session", which is the correct answer to all
 * three. A second policy in this file could only disagree with the first.
 */
const KEY = 'garajul-meu.refresh-token'

/**
 * Imported here rather than at the top of the file, and the reason was measured
 * rather than anticipated.
 *
 * <p>A static import kept the plugin in the browser bundle even though every
 * line of this module was tree-shaken out of it - the key below appeared nowhere
 * in `dist/`, while `SecureStorage`, `Keychain` and the `localStorage`-backed
 * web shim all shipped. The cause is exact: the package declares no
 * `sideEffects` field, so a bundler must assume every module in it has them, and
 * its entry point really does have one - `registerPlugin()` runs at module
 * scope, and the registration names `web: () => import('./web.js')`. A
 * side-effectful import survives its importer being dropped.
 *
 * <p>So `channel.ts` choosing at build time was **necessary and not
 * sufficient**, which nothing but the artifact check could have told us. With
 * the import inside a function, this module has no top-level side effect of its
 * own; when the cookie branch wins and the module goes, the import site goes
 * with it and no chunk is emitted.
 *
 * <p>The runtime caches a module after its first import, so only the first call
 * of a session pays anything for this.
 */
async function storage() {
  const { SecureStorage } = await import('@aparajita/capacitor-secure-storage')
  return SecureStorage
}

export const keystoreSecureStore: SecureStore = {
  read: async () => (await storage()).getItem(KEY),
  write: async (value) => { await (await storage()).setItem(KEY, value) },
  clear: async () => { await (await storage()).removeItem(KEY) },
}